name: Basic Checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - id: setup-python
      name: Set up Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade poetry
    - id: cache-poetry
      uses: actions/cache@v5
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      run: |
        poetry install

  security:
    name: Security Scan
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - id: setup-python
      name: Set up Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade poetry
    - id: cache-poetry
      uses: actions/cache@v5
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      run: |
        poetry install
    - name: Security scan
      run: |
        poetry run bandit -r hyacinth

  formatting:
    name: Formatting Scan
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - id: setup-python
      name: Set up Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade poetry
    - id: cache-poetry
      uses: actions/cache@v5
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      run: |
        poetry install
    - name: Syntax scan
      run: |
        poetry run flake8 hyacinth --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Lint scan
      run: |
        poetry run flake8 hyacinth --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  tests:
    name: Unit tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - id: setup-python
      name: Set up Python 3.11
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade poetry
    - id: cache-poetry
      uses: actions/cache@v5
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      run: |
        poetry install
    - name: Run unit tests
      run: |
        poetry run poe test
