name: Basic Checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade poetry
    - id: cache-poetry
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      run: |
        poetry install

  security:
    name: Security Scan
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade poetry
    - id: cache-pipenv
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
    - name: Security scan
      run: |
        poetry run bandit -r hyacinth

  formattting:
    name: Formatting Scan
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade poetry
    - id: cache-pipenv
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
    - name: Syntax scan
      run: |
        poetry run flake8 hyacinth --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Lint scan
      run: |
        poetry run flake8 hyacinth --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  tests:
    name: Unit tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade poetry
    - id: cache-pietry
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
    - name: Run unit tests
      run: |
        poetry run poe test
